//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Scheduler_00165658
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calender
    {
        public int c_Id { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public string wDay { get; set; }
        public Nullable<int> wNo { get; set; }
        public Nullable<int> wHour { get; set; }
        public Nullable<bool> isHoliday { get; set; }
    }
}
