//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Scheduler_00165658
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_MS_ADIEntities : DbContext
    {
        public DB_MS_ADIEntities()
            : base("name=DB_MS_ADIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agendum> Agenda { get; set; }
        public virtual DbSet<Calender> Calenders { get; set; }
        public virtual DbSet<MeetAttendy> MeetAttendies { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<Quaram> Quarams { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<urActivity> urActivities { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Venu> Venus { get; set; }
    }
}
