//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Scheduler_00165658
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int m_Id { get; set; }
        public string mTitle { get; set; }
        public Nullable<int> cId { get; set; }
        public Nullable<int> qId { get; set; }
        public Nullable<int> vId { get; set; }
        public Nullable<int> aId { get; set; }
        public Nullable<int> Start_Time { get; set; }
        public Nullable<int> Duration { get; set; }
    }
}
