//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Scheduler_00165658
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetAttendy
    {
        public int at_Id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> m_id { get; set; }
        public string Remarks { get; set; }
        public string R_Time { get; set; }
        public Nullable<int> Present { get; set; }
    }
}
