//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Scheduler_00165658
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public int o_Id { get; set; }
        public string oName { get; set; }
        public string oAddress { get; set; }
        public string oPhone { get; set; }
        public string oEmail { get; set; }
    }
}
