//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Scheduler_00165658
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quaram
    {
        public int q_Id { get; set; }
        public string qType { get; set; }
        public Nullable<int> max_Att { get; set; }
        public Nullable<int> min_Att { get; set; }
    }
}
