//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Scheduler_00165658
{
    using System;
    using System.Collections.Generic;
    
    public partial class urActivity
    {
        public int a_Id { get; set; }
        public Nullable<int> U_Id { get; set; }
        public Nullable<int> c_Id { get; set; }
        public string a_Title { get; set; }
        public Nullable<int> s_Time { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Presence { get; set; }
    }
}
