//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Scheduler_00165658
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int u_Id { get; set; }
        public string uName { get; set; }
        public string Pass { get; set; }
        public string Job_Title { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Pay_Grade { get; set; }
        public Nullable<int> Role_Id { get; set; }
    }
}
