//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Scheduler_00165658
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venu
    {
        public int v_Id { get; set; }
        public string vName { get; set; }
        public string vLocation { get; set; }
        public string vAddress { get; set; }
        public Nullable<int> Capacity { get; set; }
    }
}
